export {default as HeroSection} from './HeroSection'
export {default as PopularProducts} from './PopularProduct'
export {default as WatchBuy} from './Watch-Buy'
export {default as NewArrival} from './NewArival'
export {default as BestSeller} from './BestSeller'
export {default as Testimonial} from './Testimonial'